config/routes.rb
Rails.application.routes.draw do

  resources :orders do
    post :show_data, on: :collection
  end
  resources :statuses

  mount ShopifyApp::Engine, at: '/'
  
  # api routes
  get '/api/i18n/:locale' => 'api#i18n'

  root :to => 'orders#index'
end

app/models/session_storage.rb
class SessionStorage
  def self.store(session)
    shop = Shop.find_or_initialize_by(shopify_domain: session.url)
    shop.shopify_token = session.token
    shop.save!
    shop.id
  end

  def self.retrieve(id)
    return unless id
    shop = Shop.find(id)
    ShopifyAPI::Session.new(shop.shopify_domain, shop.shopify_token)
  rescue ActiveRecord::RecordNotFound
    nil
  end
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  include ShopifyApp::Shop
end

app/models/status.rb
class Status < ActiveRecord::Base
  validates :name, :note, presence: true
end

app/controllers/api_controller.rb
class ApiController < ActionController::Base
  
  def i18n
    # locale param was defined in config/routes.rb
    render file: "app/assets/i18n/" + params['locale']
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ShopifyApp::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def dashboard
  end
end

app/controllers/orders_controller.rb
class OrdersController < AuthenticatedController
  def index
    @orders = ShopifyAPI::Order.find(:all, params: {
      order: [params[:field], params[:order]].join(' '),
      status: params[:status]
    })

    @paginated_orders = Kaminari.paginate_array(@orders)
                                .page(params[:page])
                                .per(10)
  end

  def show
    @order = ShopifyAPI::Order.find(params[:id])
  end

  def new
    @order = ShopifyAPI::Order.new
  end

  def create
    if not params[:order][:products].blank?
      params[:order][:products].each do |key, value|
        @product = ShopifyAPI::Product.new
        @product.title     = value[:name]
        @product.body_html = value[:description]
        @product.variants  = [{price: value[:price]}]
        # Upload picture if exists
        uploaded_io = value[:picture]
        unless uploaded_io.blank?
          @picture_name = "#{Time.now.to_i}#{File.extname(uploaded_io.original_filename)}"
          product_picture = File.open(Rails.root.join('public', 'uploads', @picture_name), 'wb') do |file|
            file.write(uploaded_io.read)
          end
          @product.images = [{src: "#{root_url}uploads/#{@picture_name}"}]
        end
        @product.save
        # Remove file from disc
        File.delete(Rails.root.join('public', 'uploads', @picture_name))
      end
    end

    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Order was successfully created.' }
    end

    # respond_to do |format|
    #   if @order.save
    #     format.html { redirect_to @order, notice: 'Order was successfully created.' }
    #     format.json { render :show, order: :created, location: @order }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @order.errors, order: :unprocessable_entity }
    #   end
    # end
  end

  def show_data
  end
end

app/controllers/statuses_controller.rb
class StatusesController < AuthenticatedController
  before_action :set_status, only: [:show, :edit, :update, :destroy]

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render :edit }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url, notice: 'Status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:name, :note)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def controller?(*controller)
    controller.include?(params[:controller])
  end

  def action?(*action)
    action.include?(params[:action])
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/singleview_helper.rb
module SingleviewHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
   <title>Custom Order Pro</title>
   <%= stylesheet_link_tag 'application', media: 'all', id: "maincss" %>
   <%= csrf_meta_tags %>
</head>

<body>
   <%= yield %>
   
   <!-- =============== VENDOR SCRIPTS ===============-->
   <%= javascript_include_tag 'base' %>

   <%= javascript_include_tag 'application' %>
</body>

</html>

app/views/layouts/embedded_app.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <title>Custom Order Pro</title>

  <script src="//cdn.shopify.com/s/assets/external/app.js?<%= Time.now.strftime('%Y%m%d%H') %>"></script>
  <script type="text/javascript">
    ShopifyApp.init({
      apiKey: "<%= ShopifyApp.configuration.api_key %>",
      shopOrigin: "<%= "https://#{ @shop_session.url }" if @shop_session %>",
      debug: <%= Rails.env.development? ? 'true' : 'false' %>
    });
  </script>

  <!-- =============== VENDOR STYLES ===============-->
  <%= stylesheet_link_tag 'base' %>
  <!-- =============== APP STYLES ===============-->
  <%= stylesheet_link_tag 'application', media: 'all', id: "maincss" %>
  <%= csrf_meta_tags %>
</head>

<body>
  <script type="text/javascript">
    ShopifyApp.ready(function(){
      ShopifyApp.Bar.initialize({
        title: "<%= controller_name %>",
        icon: "<%= asset_path('faveicon.png') %>"
      });
    });
  </script>
  <div class="wrapper">
    <!-- top navbar-->
    <header class="topnavbar-wrapper">
      <%= render partial: "layouts/partials/topnavbar" %>
    </header>
    <!-- sidebar-->
    <aside class="aside">
      <%= render partial: "layouts/partials/sidebar" %>
    </aside>
    <!-- offsidebar-->
    <aside class="offsidebar hide">
      <%= render partial: "layouts/partials/offsidebar" %>
    </aside>
    <!-- Main section-->
    <section>
      <!-- Page content-->
      <div class="content-wrapper">
        <%= yield %>
      </div>
    </section>
    <!-- Page footer-->
    <footer>
      <%= render partial: "layouts/partials/footer" %>
    </footer>
  </div>
  <!-- =============== VENDOR SCRIPTS ===============-->
  <%= javascript_include_tag 'base' %>
  <!-- =============== APP SCRIPTS ===============-->
  <%= javascript_include_tag 'application' %>
</body>

</html>

app/views/layouts/partials/_footer.html.erb
<span>&copy; 2015 - Custom Order Pro</span>

app/views/layouts/partials/_offsidebar.html.erb
<!-- START Off Sidebar (right)-->
<nav>
   <div role="tabpanel">
      <!-- Nav tabs-->
      <ul role="tablist" class="nav nav-tabs nav-justified">
         <li role="presentation" class="active">
            <a href="#app-settings" aria-controls="app-settings" role="tab" data-toggle="tab">
               <em class="icon-equalizer fa-lg"></em>
            </a>
         </li>
         <li role="presentation">
            <a href="#app-chat" aria-controls="app-chat" role="tab" data-toggle="tab">
               <em class="icon-users fa-lg"></em>
            </a>
         </li>
      </ul>
      <!-- Tab panes-->
      <div class="tab-content">
         <div id="app-settings" role="tabpanel" class="tab-pane fade in active">
            <h3 class="text-center text-thin">Tab 1</h3>
         </div>
         <div id="app-chat" role="tabpanel" class="tab-pane fade">
            <h3 class="text-center text-thin">Tab 2</h3>
         </div>
      </div>
   </div>
</nav>
<!-- END Off Sidebar (right)-->

app/views/layouts/partials/_sidebar.html.erb
<!-- START Sidebar (left)-->
<div class="aside-inner">
   <nav class="sidebar">
      <!-- START sidebar nav-->
      <ul class="nav">
         <li class="nav-heading">
            <span>Main Navigation</span>
         </li>
         <li class="<%= 'active' if controller?('orders') && action?('new') %>">
            <%= link_to new_order_path, title: 'new order' do %>
               <em class="icon-plus"></em>
               <span>New Order</span>
            <% end %>
         </li>
         <li class="<%= 'active' if controller?('orders') && action?('index') %>">
            <%= link_to orders_path, title: 'orders' do %>
               <em class="icon-list"></em>
               <span>Orders</span>
            <% end %>
         </li>
         <li class="<%= 'active' if controller?('statuses') && action?('index') %>">
            <%= link_to statuses_path, title: 'statuses' do %>
               <em class="icon-tag"></em>
               <span>Statuses</span>
            <% end %>
         </li>
      </ul>
      <!-- END sidebar nav-->
   </nav>
</div>
<!-- END Sidebar (left)-->

app/views/layouts/partials/_topnavbar.html.erb
<!-- START Top Navbar-->
<nav role="navigation" class="navbar topnavbar">
   <!-- START navbar header-->
   <div class="navbar-header">
      <a href="#/" class="navbar-brand">
         <div class="brand-logo">
            <img src="<%= image_path('angle/logo.png') %>" alt="App Logo" class="img-responsive" />
         </div>
         <div class="brand-logo-collapsed">
            <img src="<%= image_path('angle/logo-single.png') %>" alt="App Logo" class="img-responsive" />
         </div>
      </a>
   </div>
   <!-- END navbar header-->
   <!-- START Nav wrapper-->
   <div class="nav-wrapper">
      <!-- START Left navbar-->
      <ul class="nav navbar-nav">
         <li>
            <!-- Button used to collapse the left sidebar. Only visible on tablet and desktops-->
            <a href="#" data-toggle-state="aside-collapsed" class="hidden-xs">
               <em class="fa fa-navicon"></em>
            </a>
            <!-- Button to show/hide the sidebar on mobile. Visible on mobile only.-->
            <a href="#" data-toggle-state="aside-toggled" data-no-persist="true" class="visible-xs sidebar-toggle">
               <em class="fa fa-navicon"></em>
            </a>
         </li>
      </ul>
      <!-- END Left navbar-->
      <!-- START Right Navbar-->
      <ul class="nav navbar-nav navbar-right">
         <!-- Search icon-->
         <li>
            <a href="#" data-search-open="">
               <em class="icon-magnifier"></em>
            </a>
         </li>
         <!-- START Offsidebar button-->
         <li>
            <a href="#" data-toggle-state="offsidebar-open" data-no-persist="true">
               <em class="icon-notebook"></em>
            </a>
         </li>
         <!-- END Offsidebar menu-->
      </ul>
      <!-- END Right Navbar-->
   </div>
   <!-- END Nav wrapper-->
   <!-- START Search form-->
   <form role="search" action="search.html" class="navbar-form">
      <div class="form-group has-feedback">
         <input type="text" placeholder="Type and hit enter ..." class="form-control" />
         <div data-search-dismiss="" class="fa fa-times form-control-feedback"></div>
      </div>
      <button type="submit" class="hidden btn btn-default">Submit</button>
   </form>
   <!-- END Search form-->
</nav>
<!-- END Top Navbar-->

app/views/orders/index.html.erb
<div class="content-heading">
   Orders
</div>
<div class="row">
    <div class="col-xs-12">
      <div class="well">
        <%= form_tag(orders_path, method: :get, class: "form-inline") do %>
          <div class="form-group">
            <%= label_tag "order" %>
            <%= select_tag "field", options_for_select([ "updated_at" ], params[:field]), class: 'form-control' %>
            <%= select_tag "order", options_for_select([ "ASC", "DESC" ], params[:order]), class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= label_tag "status", "Show" %>
            <%= select_tag "status", options_for_select([ ["All Orders", "any"], ["Open Orders", "open"], ["Closed Orders", "closed"], ["Cancelled Orders", "cancelled"] ], params[:status]), class: 'form-control' %>
          </div>
          <%= submit_tag "Submit", class: 'btn btn-default' %>
        <% end -%>
      </div>
      <table class="table">
        <thead>
          <tr>
            <th>Order number</th>
            <th>Customer Name</th>
            <th>Subtotal Price</th>
            <th>Payment</th>
          </tr>
        </thead>
        <tbody>
          <% @paginated_orders.each do |order| %>
            <tr>
              <td><%= order.number %></td>
              <td><%= [order.try(:customer).try(:first_name), order.try(:customer).try(:last_name)].join(' ') %></td>
              <td><%= [order.subtotal_price, order.currency].join(' ') %></td>
              <td><%= order.financial_status %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <%= paginate @paginated_orders %>
    </div>
</div>

app/views/orders/new.html.erb
<%= form_tag(orders_path, class: "form-horizontal", id: 'new_order', multipart: true) do %>
  <fieldset>
    <legend>Customer Info</legend>

    <div class="form-group">
      <%= label_tag 'order_customer_name', 'Customer name', class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= text_field_tag 'order[customer][name]', nil, class: "form-control", required: true %>
      </div>
    </div>

    <div class="form-group">
      <%= label_tag 'order_customer_email', 'Customer email', class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= email_field_tag 'order[customer][email]', nil, class: "form-control", required: true %>
      </div>
    </div>

    <div class="form-group">
      <%= label_tag 'order_customer_email', 'Note', class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= text_area_tag 'order[customer][note]', nil, class: "form-control" %>
      </div>
    </div>
  </fieldset>

  <fieldset class="product-information">
    <legend>Products Info</legend>
    <%= link_to raw('<i class="icon-trash"></i> Remove this product'), '#', class: 'remove-product btn btn-danger pull-right' %>
    <div class="clearfix"></div>

    <div class="form-group">
      <div class="col-sm-3">
        <%= link_to 'Select Products', '#', id: 'product-selector', class: 'btn btn-primary' %>
      </div>
      <div class="col-sm-5">
        <%= text_field_tag 'order[products][0][name]', nil, class: "form-control", placeholder: "Product name", required: true %>
      </div>
      <div class="col-sm-2">
        <%= text_field_tag 'order[products][0][price]', nil, class: "form-control", placeholder: "00.00", required: true %>
      </div>
      <div class="col-sm-2">
        <%= text_field_tag 'order[products][0][quantity]', 1, class: "form-control", required: true %>
      </div>
    </div>
    <div class="form-group">
      <%= label_tag 'order_product_description', 'Product description', class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= text_area_tag 'order[products][0][description]', nil, class: "form-control", placeholder: "Product description" %>
      </div>
    </div>
    <div class="form-group">
      <%= label_tag 'order_product_picture', 'Product picture', class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= file_field_tag "order[products][0][picture]" %>
      </div>
    </div>

  </fieldset>

  <%= link_to raw('<i class="icon-plus"></i> Add a product'), '#', class: 'add-product btn btn-success' %>
  <%= button_tag(type: "submit", class: "btn btn-success") do %>
    <i class="icon-check"></i> I'm done adding products
  <% end -%>
<% end %>

app/views/orders/show.html.erb
<% @order.line_items.each do |line_item| %>
  <%= line_item.product_id %>
<% end %>

<%= debug @order %>

app/views/orders/show_data.html.erb
<%= debug(params) %>

app/views/statuses/_form.html.erb
<%= form_for(@status, html: {class: "form-horizontal"}) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, required: true, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :note, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :note, required: true, class: "form-control" %>
    </div>
  </div>
  
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-sm btn-default" %>
    </div>
  </div>
  
<% end %>

app/views/statuses/edit.html.erb
<div class="content-heading">
  <div class="pull-right">
    <%= link_to 'Show', @status, class: "btn btn-default" %>
    <%= link_to 'Back', statuses_path, class: "btn btn-default" %>
  </div>
  Editing Status
</div>

<div class="row">
  <div class="col-xs-12">
    <%= render 'form' %>
  </div>
</div>

app/views/statuses/index.html.erb
<div class="content-heading">
   <div class="pull-right">
      <%= link_to 'New Status', new_status_path, class: "btn btn-primary" %>
   </div>
   Listing Statuses
</div>

<div class="row">
  <div class="col-xs-12">
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Note</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @statuses.each do |status| %>
          <tr>
            <td><%= status.name %></td>
            <td><%= status.note %></td>
            <td><%= link_to 'Show', status %></td>
            <td><%= link_to 'Edit', edit_status_path(status) %></td>
            <td><%= link_to 'Destroy', status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>    
  </div>
</div>

app/views/statuses/new.html.erb
<div class="content-heading">
   <div class="pull-right">
      <%= link_to 'Back', statuses_path, class: "btn btn-default" %>
   </div>
   New Status
</div>

<div class="row">
  <div class="col-xs-12">
    <%= render 'form' %>
  </div>
</div>

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @status.name %>
</p>

<p>
  <strong>Note:</strong>
  <%= @status.note %>
</p>

<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>